server: 
  port: 8080
spring: 
  application:
    name: gateway
  cloud:
    #Spring Cloud Gateway路由配置方式
    gateway:
      #是否与服务组建进行结合，通过serviceId(必须设置成大写)转发到具体的服务实例
      #默认为false，设置为true便开启通过服务中心的自动根据serviceId创建路由的功能
      discovery:
        #路由的访问方式：http://Gateway_Host:Gateway_port/大写的serviceId/**
        locator:
          enabled: true
          
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
    
feign: 
  hystrix: 
    #开启熔断器
    enable: true
